import { spawn } from "node:child_process";
import { mkdir } from "node:fs/promises";
import { dirname, isAbsolute, join } from "node:path";
import {
  gradientGeometry,
  parseCssColor,
  type FrameGeometry,
  type FrameStyle,
} from "@ossclip/core/browser";

/**
 * The four PNGs the ffmpeg path composites around the picture.
 *
 * They are generated by ffmpeg itself (`-f lavfi` one-shots) rather than by a
 * rasterizer we'd have to own: `gblur` is a real Gaussian — the same shape
 * CSS's `box-shadow` describes — and `geq` gives us the per-pixel math in the
 * one language that already has to be on the box. Probe
 * (Temp/bgprobe/ffassets.py) validated every expression against reference
 * pixels before any of this shipped.
 *
 * Three probe findings are baked into the expressions below:
 *
 *  A. ffmpeg's `gradients` filter is NON-DETERMINISTIC — three runs of the
 *     same command produced three different hashes (`speed=0` only stops the
 *     temporal animation; the spatial generation is still randomly seeded).
 *     Gradients therefore come from `geq`, which is a pure function of X/Y.
 *  B. `geq` TRUNCATES its float result to uint8 while browsers round, so
 *     every colour lerp carries an explicit `+0.5`.
 *  C. The antialias band on a rounded rect is `0.5 - sd` against the
 *     PRE-ROUNDED signed distance. `radius + 0.5 - sd` belongs to the
 *     unrounded-box formulation and inflates the shape by the full radius.
 *
 * Every asset is a SINGLE-FRAME input to the main graph. Nothing is `-loop`ed:
 * framesync's defaults (`eof_action=repeat`, `shortest=false`) repeat a finite
 * secondary input for the whole clip, which is why the graph ends at the
 * video's own EOF without a `-t` — and why there is no per-frame PNG decode
 * (the `-loop 1` that made a static background 4.6x slower than it needed to
 * be). Also why the mask carries no `-framerate`-less input: a static image
 * without one silently declares 25fps and drags the output rate with it.
 */

export interface FrameAssetRequest {
  style: FrameStyle;
  geometry: FrameGeometry;
  /** The stage colour, used when `background.type === "none"`. */
  themeBg: string;
}

export interface FrameAssetPlan {
  /** Relative to the render's public dir. */
  background: string;
  /** Content-box sized; only when the corners are actually rounded. */
  mask?: string;
  /** Full-frame, already offset AND blurred. */
  shadow?: string;
  /** Full-frame stroke. */
  border?: string;
  /** Argv for the ffmpeg that writes each of the above. */
  commands: Array<{ out: string; args: string[] }>;
}

export const FRAME_ASSET_DIR = "frame";

/** ffmpeg numbers: integers without a trailing `.0`, floats trimmed. */
function n(v: number): string {
  if (Number.isInteger(v)) return String(v);
  return String(Number(v.toFixed(4)));
}

function hex2(c: { r: number; g: number; b: number }): string {
  const p = (v: number) => Math.max(0, Math.min(255, v)).toString(16).padStart(2, "0");
  return `0x${p(c.r)}${p(c.g)}${p(c.b)}`;
}

/**
 * Signed distance to a rounded rect centred at (cx,cy), as a colon-free `geq`
 * expression. lavfi parses an input description with `:` as an option
 * separator before quotes ever protect it, so no colon may appear in here —
 * which is also why there is no variable binding and `abs(X-…)` repeats.
 */
function sdRoundedRect(cx: number, cy: number, halfW: number, halfH: number, radius: number): string {
  const qx = `(abs(X-${n(cx)})-${n(halfW - radius)})`;
  const qy = `(abs(Y-${n(cy)})-${n(halfH - radius)})`;
  return `hypot(max(${qx},0),max(${qy},0))+min(max(${qx},${qy}),0)-${n(radius)}`;
}

/** `clamp(0.5 - sd, 0, 1)` — probe finding C. */
function fillExpr(sd: string): string {
  return `min(max(0.5-(${sd}),0),1)`;
}

/** Rounded rect covering the whole mask canvas (which IS the content box). */
function maskArgs(g: FrameGeometry): string {
  const sd = sdRoundedRect(g.content.width / 2, g.content.height / 2, g.content.width / 2, g.content.height / 2, g.radius);
  return `255*${fillExpr(sd)}`;
}

/** Rounded rect at the content box, shifted by the shadow offset. */
function shadowArgs(g: FrameGeometry, style: FrameStyle, colorAlpha: number): string {
  const cx = g.content.x + g.content.width / 2 + style.shadowOffsetX;
  const cy = g.content.y + g.content.height / 2 + style.shadowOffsetY;
  const sd = sdRoundedRect(cx, cy, g.content.width / 2, g.content.height / 2, g.radius);
  // colorAlpha: `frameShadowCss` composites `c.a * shadowOpacity` in the
  // preview, so the rasteriser has to fold the shadow colour's own alpha in
  // too or an rgba() shadowColor exports opaque (same class of bug as the
  // border's).
  return `255*${n(style.shadowOpacity * colorAlpha)}*${fillExpr(sd)}`;
}

/**
 * A stroke of visible thickness `borderWidth`, centred on the content-box
 * path — ScreenArc draws `lineWidth = borderWidth * 2` so half the stroke
 * lands inside and half outside (`renderer.ts:245-252`).
 */
function borderArgs(g: FrameGeometry, colorAlpha: number): string {
  const sd = sdRoundedRect(
    g.content.x + g.content.width / 2,
    g.content.y + g.content.height / 2,
    g.content.width / 2,
    g.content.height / 2,
    g.radius,
  );
  // colorAlpha: the preview's `frameBorderCss` emits the raw `rgba(...)`, so
  // a border colour with alpha < 1 is translucent there. The stroke coverage
  // below is the AA band only — the colour's own alpha has to scale it or the
  // default `rgba(255,255,255,0.2)` exports as solid white.
  return `255*${n(colorAlpha)}*min(max(${n(g.borderWidth + 0.5)}-abs(${sd}),0),1)`;
}

/** Probe finding B: round like a browser rather than truncating like geq. */
function lerpChannel(t: string, from: number, to: number): string {
  return `min(max(${n(from)}+(${n(to)}-${n(from)})*(${t})+0.5,0),255)`;
}

/**
 * Per-channel `geq` expressions for a background gradient. `t` is the
 * normalised position along the gradient LINE, so the rasteriser and CSS draw
 * the same line (both take it from `gradientGeometry`).
 */
export function gradientGeqExprs(
  style: FrameStyle,
  w: number,
  h: number,
): { r: string; g: string; b: string } | undefined {
  const bg = style.background;
  if (bg.type !== "gradient") return undefined;
  const from = parseCssColor(bg.start);
  const to = parseCssColor(bg.end);
  if (!from || !to) return undefined;
  const geo = gradientGeometry(bg.direction, w, h);
  const swap = bg.direction === "circle-in";
  const a = swap ? to : from;
  const b = swap ? from : to;
  let t: string;
  if (geo.kind === "radial") {
    const d = `min(max(hypot(abs(X-${n(geo.cx)}),abs(Y-${n(geo.cy)}))/${n(geo.radius)},0),1)`;
    t = d;
  } else {
    const dx = geo.x1 - geo.x0;
    const dy = geo.y1 - geo.y0;
    const denom = dx * dx + dy * dy;
    t = `min(max(((${n(dx)})*(X-${n(geo.x0)})+(${n(dy)})*(Y-${n(geo.y0)}))/${n(denom)},0),1)`;
  }
  return { r: lerpChannel(t, a.r, b.r), g: lerpChannel(t, a.g, b.g), b: lerpChannel(t, a.b, b.b) };
}

function colorSource(hex: string, w: number, h: number): string {
  return `color=c=${hex}:s=${w}x${h},format=rgba`;
}

function writePngCommand(out: string, input: string, extraFilter?: string): { out: string; args: string[] } {
  const chain = extraFilter ? `${input},${extraFilter}` : input;
  return { out, args: ["-v", "error", "-y", "-f", "lavfi", "-i", chain, "-frames:v", "1", out] };
}

/**
 * What to build and how. Pure — the caller does the spawning — so the whole
 * plan is assertable without an ffmpeg on the box.
 *
 * Each asset is skipped when it would be a no-op, which keeps the main graph's
 * input list as short as the settings allow: a `radius` of 0 means no mask and
 * no `alphamerge` at all.
 */
export function buildFrameAssetPlan(req: FrameAssetRequest, publicDir: string): FrameAssetPlan {
  const { style, geometry: g } = req;
  const dir = join(publicDir, FRAME_ASSET_DIR);
  const rel = (name: string) => `${FRAME_ASSET_DIR}/${name}`;
  const abs = (name: string) => join(dir, name);
  const commands: Array<{ out: string; args: string[] }> = [];

  // Background: always built, even for `none` — the padding ring needs a
  // colour in BOTH renderers, and the stage's own theme token is that colour.
  const bgOut = abs("background.png");
  const bg = style.background;
  if (bg.type === "color") {
    const c = parseCssColor(bg.color);
    commands.push(
      writePngCommand(bgOut, c ? colorSource(hex2(c), g.width, g.height) : colorSource("0x000000", g.width, g.height)),
    );
  } else if (bg.type === "gradient") {
    const e = gradientGeqExprs(style, g.width, g.height);
    commands.push(
      writePngCommand(
        bgOut,
        colorSource("0x000000", g.width, g.height),
        e ? `geq=r='${e.r}':g='${e.g}':b='${e.b}':a='255'` : undefined,
      ),
    );
  } else if (bg.type === "image" || bg.type === "wallpaper") {
    // Rasterised to the frame here rather than scaled inside the main graph:
    // `cover` is NOT a value `force_original_aspect_ratio` accepts (only
    // disable|decrease|increase), so cover-fit is `increase` + `crop`.
    // The name is relative to the render's public dir (the `videoFileName`
    // contract), and ffmpeg resolves `-i` against the CWD, so it is joined
    // here rather than left for the command line.
    commands.push({
      out: bgOut,
      args: [
        "-v", "error", "-y",
        "-i", isAbsolute(bg.file) ? bg.file : join(publicDir, bg.file),
        "-vf",
        `scale=${g.width}:${g.height}:force_original_aspect_ratio=increase:flags=lanczos,crop=${g.width}:${g.height}`,
        "-frames:v", "1",
        bgOut,
      ],
    });
  } else {
    commands.push(writePngCommand(bgOut, colorSource(req.themeBg, g.width, g.height)));
  }

  const plan: FrameAssetPlan = { background: rel("background.png"), commands };

  if (g.radius > 0) {
    const out = abs("mask.png");
    const cw = g.content.width;
    const ch = g.content.height;
    commands.push({
      out,
      args: [
        "-v", "error", "-y",
        "-f", "lavfi",
        "-i", `color=c=black:s=${cw}x${ch},format=gray,geq=lum='${maskArgs(g)}'`,
        "-frames:v", "1",
        out,
      ],
    });
    plan.mask = rel("mask.png");
  }

  if (style.shadowBlur > 0 && style.shadowOpacity > 0) {
    const out = abs("shadow.png");
    const color = parseCssColor(style.shadowColor) ?? { r: 0, g: 0, b: 0, a: 1 };
    // CSS blur radius B is a Gaussian with sigma = B/2.
    const sigma = style.shadowBlur / 2;
    commands.push(writePngCommand(
      out,
      `color=c=${hex2(color)}:s=${g.width}x${g.height},format=rgba,geq=r='0':g='0':b='0':a='${shadowArgs(g, style, color.a)}'`,
      `gblur=sigma=${n(sigma)}`,
    ));
    plan.shadow = rel("shadow.png");
  }

  if (g.borderWidth > 0) {
    const out = abs("border.png");
    const color = parseCssColor(style.borderColor) ?? { r: 255, g: 255, b: 255, a: 0 };
    commands.push(writePngCommand(
      out,
      `color=c=${hex2(color)}:s=${g.width}x${g.height},format=rgba,geq=r='${color.r}':g='${color.g}':b='${color.b}':a='${borderArgs(g, color.a)}'`,
    ));
    plan.border = rel("border.png");
  }

  return plan;
}

/**
 * Build anything the plan still needs, then hand back the resolved paths.
 * Regenerates rather than caching: four one-shots are a couple of seconds
 * against a render that takes minutes, and a cache key would have to encode
 * every input that reaches `geq` to be safe.
 */
export async function ensureFrameAssets(
  req: FrameAssetRequest,
  publicDir: string,
  ffmpegBin: string,
): Promise<FrameAssetPlan> {
  const plan = buildFrameAssetPlan(req, publicDir);
  for (const cmd of plan.commands) {
    await mkdir(dirname(cmd.out), { recursive: true });
    await new Promise<void>((resolvePromise, rejectPromise) => {
      const child = spawn(ffmpegBin, cmd.args, { stdio: ["ignore", "ignore", "pipe"] });
      let err = "";
      child.stderr.on("data", (d: Buffer) => (err += d.toString()));
      child.on("error", rejectPromise);
      child.on("close", (code) => {
        if (code === 0) resolvePromise();
        else rejectPromise(new Error(`frame asset failed (exit ${code}):\n${cmd.args.join(" ")}\n${err}`));
      });
    });
  }
  return plan;
}
