import { z } from "zod/v4";

/**
 * ScreenArc-style frame styling: a background plus the padding / radius /
 * shadow / border chrome around the picture.
 *
 * The whole key is ABSENT-MEANS-OFF. `OverrideDocSchema` declares it
 * `.optional()` with NO default, so every overrides.json written before the
 * feature existed parses byte-identically — and a run that never enabled it
 * writes no `frameStyle` into render-props.json at all, so its pixels are
 * indistinguishable from a pre-feature render (the `captionsHidden` rule).
 * Present-but-empty is a full set of values, though: every field below has a
 * default, so `{}` parses to ScreenArc's shipped defaults. That is what
 * "seed on first use" means — the editor writes `{}` when the user first
 * reaches for the panel and gets ScreenArc's look, and "reset" writes `{}`.
 *
 * Probe (Temp/bgprobe/): the four assets this drives are generated by ffmpeg
 * `geq` one-shots, not by a hand-written rasterizer. Three findings from
 * that probe are load-bearing here and in `@ossclip/renderer`:
 *   A. ffmpeg's `gradients` filter is NON-DETERMINISTIC (three runs of the
 *      same command produced three different hashes — `speed=0` only stops
 *      the temporal animation, the spatial generation is still randomly
 *      seeded). Reproducible assets therefore require `geq`.
 *   B. `geq` TRUNCATES floats to uint8 while browsers round, so every lerp
 *      needs an explicit `+0.5` to match the CSS the preview draws.
 *   C. The antialias band on a rounded rect is `0.5 - sd` on the PRE-ROUNDED
 *      signed distance; `radius + 0.5 - sd` inflates the shape by the full
 *      radius (it belongs to the unrounded-box formulation).
 */

/** ScreenArc's ten gradient presets (`BackgroundSettings.tsx:127-138`). */
export const GRADIENT_DIRECTIONS = [
  "to bottom",
  "to top",
  "to right",
  "to left",
  "to bottom right",
  "to top left",
  "to bottom left",
  "to top right",
  "circle-out",
  "circle-in",
] as const;
export type GradientDirection = (typeof GRADIENT_DIRECTIONS)[number];

/**
 * What sits behind the picture.
 *
 * `file` is a name inside the render's public dir, the `videoFileName` and
 * `coverInVideo.fileName` contract — never an absolute path, so a
 * render-props.json stays portable across machines.
 */
export const BackgroundSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("none") }),
  z.object({ type: z.literal("color"), color: z.string().default("#ffffff") }),
  z.object({
    type: z.literal("gradient"),
    start: z.string().default("#6366f1"),
    end: z.string().default("#9ca9ff"),
    direction: z.enum(GRADIENT_DIRECTIONS).default("to bottom"),
  }),
  z.object({ type: z.literal("image"), file: z.string().min(1) }),
  // A CATALOGUED image, distinct from `image` because its `file` never comes
  // from the user's disk: it names one of the 17 bundled wallpapers and the
  // producer copies it out of the installed package. Keeping the two apart
  // means a staging path can tell "copy from the catalog" from "copy from
  // wherever this person pointed" without a path-prefix guess — the
  // parse-never-coerce rule applied to file locations.
  z.object({ type: z.literal("wallpaper"), file: z.string().min(1) }),
]);

export type Background = z.infer<typeof BackgroundSchema>;

/** How many wallpapers ship, and what they are called. */
export const WALLPAPER_COUNT = 17;
const WALLPAPER_PADDED = (n: number) => `wallpaper-${String(n).padStart(4, "0")}.jpg`;

/** Served-relative path of a wallpaper's full-size image. */
export function wallpaperFile(n: number): string {
  return `wallpapers/images/${WALLPAPER_PADDED(n)}`;
}
/** Served-relative path of a wallpaper's picker thumbnail. */
export function wallpaperThumb(n: number): string {
  return `wallpapers/thumbnails/${WALLPAPER_PADDED(n)}`;
}
/** 1-based index of a wallpaper path, or 0 when the name is not one. */
export function wallpaperIndex(file: string): number {
  const m = /wallpaper-(\d{4})\.jpg$/.exec(file);
  if (!m) return 0;
  const n = Number(m[1]);
  return n >= 1 && n <= WALLPAPER_COUNT ? n : 0;
}

/**
 * `#rgb`/`#rrggbb`/`#rrggbbaa`, `rgb()` and `rgba()`. Anything else is
 * UNDEFINED rather than guessed at: the caller warns and falls back, because
 * a hand-edited overrides.json that says `background: "bluish"` must not
 * silently become black (the parse-never-coerce rule).
 */
export function parseCssColor(
  input: string,
): { r: number; g: number; b: number; a: number } | undefined {
  const s = input.trim().toLowerCase();
  const hex = /^#([0-9a-f]{3,8})$/.exec(s);
  if (hex) {
    const d = hex[1]!;
    const expand = (x: string) => (x.length === 1 ? x + x : x);
    if (d.length === 3 || d.length === 4) {
      const r = expand(d[0]!);
      const g = expand(d[1]!);
      const b = expand(d[2]!);
      const a = expand(d[3] ?? "f");
      return {
        r: parseInt(r, 16),
        g: parseInt(g, 16),
        b: parseInt(b, 16),
        a: parseInt(a, 16) / 255,
      };
    }
    if (d.length === 6 || d.length === 8) {
      const num = (from: number, to: number) => parseInt(d.slice(from, to), 16);
      return {
        r: num(0, 2),
        g: num(2, 4),
        b: num(4, 6),
        a: d.length === 8 ? num(6, 8) / 255 : 1,
      };
    }
    return undefined;
  }
  const fn = /^(rgba?)\(\s*([0-9.]+)[\s,]+([0-9.]+)[\s,]+([0-9.]+)\s*(?:[,/]\s*([0-9.]+)%?)?\s*\)$/.exec(s);
  if (fn) {
    const chan = (x: string) => Math.max(0, Math.min(255, Math.round(Number(x))));
    let a = 1;
    if (fn[5] !== undefined) {
      a = fn[5].endsWith("%") ? Number(fn[5].slice(0, -1)) / 100 : Number(fn[5]);
      a = Math.max(0, Math.min(1, a));
    }
    return { r: chan(fn[2]!), g: chan(fn[3]!), b: chan(fn[4]!), a };
  }
  return undefined;
}

/** Per-control defaults, ScreenArc's `DEFAULTS.FRAME` (`constants.ts:62-79`). */
export const FRAME_STYLE_DEFAULTS = {
  padding: 5,
  radius: 16,
  borderWidth: 4,
  borderColor: "rgba(255, 255, 255, 0.2)",
  shadowBlur: 35,
  shadowOffsetX: 0,
  shadowOffsetY: 15,
  shadowColor: "#000000",
  shadowOpacity: 0.8,
} as const;

export const FrameStyleSchema = z.object({
  background: BackgroundSchema.default({ type: "none" }),
  /** Percent of the output frame, per axis (`0`-`30`). */
  padding: z.number().min(0).max(30).default(FRAME_STYLE_DEFAULTS.padding),
  /** Corner radius in OUTPUT pixels — same unit in CSS and in the mask PNG. */
  radius: z.number().min(0).max(100).default(FRAME_STYLE_DEFAULTS.radius),
  borderWidth: z.number().min(0).max(20).default(FRAME_STYLE_DEFAULTS.borderWidth),
  borderColor: z.string().default(FRAME_STYLE_DEFAULTS.borderColor),
  /** CSS blur radius; the rasterized sigma is `blur / 2` (CSS's own mapping). */
  shadowBlur: z.number().min(0).max(200).default(FRAME_STYLE_DEFAULTS.shadowBlur),
  shadowOffsetX: z.number().min(-200).max(200).default(FRAME_STYLE_DEFAULTS.shadowOffsetX),
  shadowOffsetY: z.number().min(-200).max(200).default(FRAME_STYLE_DEFAULTS.shadowOffsetY),
  shadowColor: z.string().default(FRAME_STYLE_DEFAULTS.shadowColor),
  shadowOpacity: z.number().min(0).max(1).default(FRAME_STYLE_DEFAULTS.shadowOpacity),
});
export type FrameStyle = z.infer<typeof FrameStyleSchema>;

/** ScreenArc's shipped look — what "reset" writes back. */
export function defaultFrameStyle(): FrameStyle {
  return FrameStyleSchema.parse({});
}

/**
 * Background is one of the four kinds, or the feature is off entirely.
 * `FrameStyle` always carries a background after parsing, so the discriminator
 * never has to be re-checked by consumers.
 */
export function frameStyleEnabled(style: FrameStyle | undefined): style is FrameStyle {
  return style !== undefined;
}

export interface FrameGeometry {
  /** Inset applied to the stage on each axis, in output pixels. */
  padX: number;
  padY: number;
  /**
   * The box the picture lives in — and therefore the box the radius, border
   * and shadow hug. Without `source` this is the padded stage verbatim; with
   * it, the padded stage shrunk to the source's own aspect and centred, so a
   * 1280x1024 take inside a 1920x1080 padding gets a border that sits ON the
   * picture instead of out in the background, two hundred pixels away.
   */
  content: { x: number; y: number; width: number; height: number };
  /** Corner radius in output pixels (clamped to half the smallest content edge). */
  radius: number;
  borderWidth: number;
  width: number;
  height: number;
}

/**
 * The ONE place the padded box is computed. ScreenArc insets the frame by a
 * percentage of each axis independently (`renderer.ts:185-190`), so a 5% pad
 * is 54px on a 1080-wide frame and 96px on a 1920-tall one — non-uniform, and
 * a copy of that math in the renderer would be a second opinion on the
 * geometry the preview already drew.
 *
 * The radius is clamped to half the smaller content edge: CSS silently
 * reduces an over-large border-radius, while the `geq` mask would not, and
 * the two would disagree at exactly the sizes where the clamp engages.
 *
 * `source` (2026-09-27): the padded stage is the OUTPUT's aspect, the picture
 * is the SOURCE's, and on any mismatch the picture is only ever fitted into
 * that stage — it never reaches its edges. Left as-is, every chrome layer
 * would be drawn around the empty stage and float in the background. Passing
 * the source shrinks `content` to the fitted picture (contain maths: scale to
 * whichever axis binds first, then centre), so all three layers land on the
 * video. Omit it and the box is the padded stage, which is still correct
 * whenever the source is already the output's aspect.
 */
export function frameGeometry(
  style: FrameStyle,
  out: { width: number; height: number },
  source?: { width: number; height: number },
): FrameGeometry {
  const padX = Math.round((out.width * style.padding) / 100);
  const padY = Math.round((out.height * style.padding) / 100);
  let content = {
    x: padX,
    y: padY,
    width: Math.max(1, out.width - 2 * padX),
    height: Math.max(1, out.height - 2 * padY),
  };
  if (source && source.width > 0 && source.height > 0) {
    const scale = Math.min(content.width / source.width, content.height / source.height);
    const width = Math.max(1, Math.round(source.width * scale));
    const height = Math.max(1, Math.round(source.height * scale));
    content = {
      x: content.x + Math.round((content.width - width) / 2),
      y: content.y + Math.round((content.height - height) / 2),
      width,
      height,
    };
  }
  const radius = Math.min(style.radius, Math.min(content.width, content.height) / 2);
  return {
    padX,
    padY,
    content,
    radius,
    borderWidth: style.borderWidth,
    width: out.width,
    height: out.height,
  };
}

export type GradientGeometry =
  | { kind: "linear"; x0: number; y0: number; x1: number; y1: number }
  | { kind: "radial"; cx: number; cy: number; radius: number };

/**
 * The gradient line, in output pixels — the rasterizer's input and the exact
 * line CSS would draw.
 *
 * CSS does not simply run a diagonal from corner to corner: it projects the
 * corners onto the gradient LINE and lengthens it so the perpendicular
 * through the far corner lands at t=1. The formula below is that projection
 * for a unit direction `u`, `L = |W·ux| + |H·uy|`, start = centre − u·L/2.
 * For `to bottom right` it collapses to the corner pair (0,0)→(W,H), which
 * is what the probe verified bit-exactly.
 *
 * Radial presets use `circle closest-side at centre`, so the radius is half
 * the smaller edge — `circle-in` is the same circle with the stops swapped,
 * because CSS cannot express a reversed radius.
 */
export function gradientGeometry(direction: GradientDirection, w: number, h: number): GradientGeometry {
  const cx = w / 2;
  const cy = h / 2;
  if (direction === "circle-out" || direction === "circle-in") {
    return { kind: "radial", cx, cy, radius: Math.min(w, h) / 2 };
  }
  const [ux, uy] = unitVector(direction, { width: w, height: h });
  // CSS Images 3 §3.1.1: `abs(W*sin(A)) + abs(H*cos(A))` — the line's length,
  // so a stop at 0% and one at 100% land exactly on the perpendiculars through
  // the far corners.
  const len = Math.abs(w * ux) + Math.abs(h * uy);
  return {
    kind: "linear",
    x0: cx - (ux * len) / 2,
    y0: cy - (uy * len) / 2,
    x1: cx + (ux * len) / 2,
    y1: cy + (uy * len) / 2,
  };
}

/**
 * The gradient line's DIRECTION for one of the ten presets.
 *
 * The four EDGE keywords are box-independent. The four CORNER keywords are
 * not: CSS Images 3 §3.1.1 says a corner's line is "perpendicular to a line
 * intersecting the two neighboring corners of the gradient box", which works
 * out to `(side*height, side*width)` — and only collapses to the obvious 45°
 * when the box happens to be square. On a 1080x1920 portrait frame,
 * `to bottom right` points (0.872, 0.490), not (0.707, 0.707): using 45°
 * here would have made the rasteriser and the preview disagree on every
 * non-square output, which is most of them.
 */
function unitVector(direction: GradientDirection, box: { width: number; height: number }): [number, number] {
  switch (direction) {
    case "to right":
      return [1, 0];
    case "to left":
      return [-1, 0];
    case "to bottom":
      return [0, 1];
    case "to top":
      return [0, -1];
    case "to bottom right":
      return norm(box.height, box.width);
    case "to top left":
      return norm(-box.height, -box.width);
    case "to bottom left":
      return norm(-box.height, box.width);
    case "to top right":
      return norm(box.height, -box.width);
    default:
      return [0, 1];
  }
}

function norm(x: number, y: number): [number, number] {
  const m = Math.hypot(x, y);
  return [x / m, y / m];
}

/**
 * The CSS `background` value for the preview. The rasterizer does NOT share
 * this string — it consumes `gradientGeometry` — so a browser that computes
 * its own gradient line and a `geq` that evaluates ours can still agree,
 * because both were handed the same line.
 */
export function frameBackgroundCss(
  bg: Background,
  resolveImage?: (file: string) => string | undefined,
): string | undefined {
  switch (bg.type) {
    case "none":
      return undefined;
    case "color":
      return bg.color;
    case "gradient": {
      const stops = `${bg.start}, ${bg.end}`;
      if (bg.direction === "circle-out") return `radial-gradient(circle closest-side at center, ${stops})`;
      if (bg.direction === "circle-in")
        return `radial-gradient(circle closest-side at center, ${bg.end}, ${bg.start})`;
      return `linear-gradient(${bg.direction}, ${stops})`;
    }
    case "image":
    case "wallpaper": {
      const url = resolveImage?.(bg.file);
      if (!url) return undefined;
      // `center / cover no-repeat` mirrors the rasterizer's
      // `force_original_aspect_ratio=increase` + centre `crop` (frame-assets.ts):
      // a bare url() would paint at native size — a 6016px wallpaper tiles
      // and reads as a random zoomed crop of the image.
      return `url(${JSON.stringify(url)}) center / cover no-repeat`;
    }
  }
}

/**
 * CSS `box-shadow` for the preview. `gblur`'s sigma is `blur / 2` and CSS's
 * blur radius is likewise `2*sigma`, so `shadowBlur` is passed through to both
 * unchanged — that equivalence is the whole reason the probe measured the
 * default blur 35 as an exact match rather than an approximation.
 *
 * Returns `undefined` when the shadow is off, which is also what the renderer
 * does: `ensureFrameAssets` skips writing `shadow.png` on the same two
 * conditions, so the preview and the output drop the layer together.
 */
export function frameShadowCss(style: FrameStyle): string | undefined {
  if (style.shadowBlur <= 0 || style.shadowOpacity <= 0) return undefined;
  const c = parseCssColor(style.shadowColor) ?? { r: 0, g: 0, b: 0, a: 1 };
  const a = c.a * style.shadowOpacity;
  if (a <= 0) return undefined;
  return `${style.shadowOffsetX}px ${style.shadowOffsetY}px ${style.shadowBlur}px rgba(${c.r}, ${c.g}, ${c.b}, ${a})`;
}

/**
 * The border straddles the content-box edge in ScreenArc (`lineWidth =
 * borderWidth * 2` drawn centred on the path), so the preview positions it
 * `borderWidth / 2` outside the padded box to land on the same pixels. Callers
 * clamp the inset to `>= 0`: at padding 0 the stroke is half-clipped in the
 * rasterizer too, and a negative inset would escape the frame.
 */
export function frameBorderCss(style: FrameStyle): string | undefined {
  if (style.borderWidth <= 0) return undefined;
  return `${style.borderWidth}px solid ${style.borderColor}`;
}
